trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: -1
model:
  gaussian:
    optimization:
      feature_extra_lr_init: 2e-3
    sh_degree: 0
    extra_feature_dims: 64
  renderer:
    class_path: internal.renderers.gsplat_distributed_appearance_embedding_renderer.GSplatDistributedAppearanceEmbeddingRenderer
    init_args:
      appearance:
        n_appearances: 1024
        is_view_dependent: true
      appearance_optimization:
        warm_up: 0
  density: internal.density_controllers.distributed_vanilla_density_controller.DistributedVanillaDensityController
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser:
    class_path: Colmap
    init_args:
      split_mode: "reconstruction"