model:
  gaussian:
    sh_degree: 2
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
        lambda_normal: 0.0125
        depth_ratio: 1.0
        init: 0.5
        final_factor: 0.005
        depth_loss_type: ssim
        diable_trimming: true
trainer:
  check_val_every_n_epoch: 20
  max_steps: 30000
data:
  type: estimated_depth_colmap_block
  path: data/GauU_Scene/LFLS
  params:
    estimated_depth_colmap_block:
      split_mode: experiment
      eval_image_select_mode: ratio
      eval_ratio: 0.1
      down_sample_factor: 3.4175