# trim too much, can be lower
trainer:
  check_val_every_n_epoch: 20
  max_steps: 60_000
model:
  init_from: outputs/citygsv2_mc_street_coarse/checkpoints/epoch=8-step=30000.ckpt
  gaussian:
    optimization:
      feature_extra_lr_max_steps: 60_000
      position_lr_max_steps: 60_000
      position_lr_init: 0.8e-5
      position_lr_final: 0.8e-6
      scaling_lr: 0.0025
      densification_interval: 1000
      opacity_reset_interval: 30_000
      densify_from_iter: 500
      densify_until_iter: 30_000
      densify_grad_threshold: 0.000075
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
        max_steps: 60_000
        lambda_normal: 0.0125
        depth_ratio: 1.0
        normal_regularization_from_iter: 0
        init: 0.5
        final_factor: 0.05
        diable_trimming: true
        depth_loss_type: ssim
        depth_norm: true
data:
  type: estimated_depth_colmap_block
  path: data/matrix_city/street/train/block_A
  params:
    estimated_depth_colmap_block:
      image_list: data/matrix_city/street/train/block_A/partition/5_4_1_official
      down_sample_factor: 1
      depth_scale_lower_bound: 0.01
      depth_scale_upper_bound: 50.0
      num_threshold: 25000
      content_threshold: 0.01
      block_dim:
      - 5
      - 4
      - 1
      aabb:
      - -600
      - -400
      - -10
      - -300
      - -200
      - 500
save_iterations:
- 30000
- 60000