max_steps: 40000
data:
  params:
    val_max_num_images_to_cache: -1
    test_max_num_images_to_cache: -1
model:
  renderer:
    class_path: internal.renderers.deformable_renderer.DeformableRenderer
    init_args:
      deform_network:
        tcnn: false
      time_encoding:
        n_frequencies: 6
        n_layers: 0
        n_neurons: 0
      optimization:
        enable_ast: true